import streamlit as st
from agent import PropertyLawAgent
import time
import os
from dotenv import load_dotenv
import tempfile
import shutil

# Load environment variables from .env file (for local development)
load_dotenv()

# Set page config
st.set_page_config(
    page_title="FishyAI - Property Law Assistant",
    page_icon="🐟",
    layout="wide"
)

# Custom CSS for a prettier interface
st.markdown("""
<style>
    /* Main Container Styling */
    .main {
        padding: 1.5rem;
    }
    
    /* Header Styling */
    .stTitle {
        color: #1e3a8a;
        margin-bottom: 0.5rem !important;
    }
    
    /* Chat Message Styling */
    .stChatMessage {
        padding: 0.75rem 0;
    }
    
    /* Custom message container with shadow */
    .message-container {
        padding: 1rem;
        border-radius: 0.8rem;
        margin-bottom: 0.75rem;
        box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        animation: fadeIn 0.5s;
    }
    
    /* User message styling */
    .user-message {
        background-color: #e0f2fe;
        border-left: 4px solid #0ea5e9;
    }
    
    /* Assistant message styling */
    .assistant-message {
        background-color: #f3f4f6;
        border-left: 4px solid #6366f1;
    }
    
    /* Sources box styling */
    .sources-box {
        background-color: #f8fafc;
        border-radius: 0.5rem;
        padding: 0.75rem;
        margin-top: 0.5rem;
        border-left: 3px solid #0ea5e9;
        font-size: 0.9rem;
    }
    
    /* Input box styling */
    .stChatInputContainer {
        padding-top: 1rem;
        border-top: 1px solid #e5e7eb;
    }
    
    /* Animation */
    @keyframes fadeIn {
        0% { opacity: 0; transform: translateY(10px); }
        100% { opacity: 1; transform: translateY(0); }
    }
    
    /* Description box */
    .description-box {
        background-color: #f0f9ff;
        border-radius: 0.5rem;
        padding: 1rem;
        margin: 1rem 0;
        border-left: 4px solid #0ea5e9;
    }
    
    /* Response time indicator */
    .response-time {
        font-size: 0.8rem;
        color: #6b7280;
        text-align: right;
        margin-top: 0.25rem;
    }
</style>
""", unsafe_allow_html=True)

# Get API key from environment variable first, then fall back to Streamlit secrets
api_key = os.getenv("OPENAI_API_KEY") or st.secrets.get("secrets", {}).get("OPENAI_API_KEY")

if not api_key:
    st.error("""
    OPENAI_API_KEY not found. Please set it as an environment variable:
    
    For local development:
    1. Create a .env file in the root directory
    2. Add: OPENAI_API_KEY=your_api_key_here
    
    For production:
    Set the OPENAI_API_KEY environment variable in your deployment platform
    """)
    st.stop()

# Initialize session state
if 'agent' not in st.session_state:
    try:
        with st.spinner("Initializing Property Law Assistant..."):
            st.session_state.agent = PropertyLawAgent("pdfs")
            success, message = st.session_state.agent.load_pdfs()
            st.session_state.initial_load_message = message
    except Exception as e:
        st.error(f"Error initializing agent: {str(e)}")
        st.stop()

if 'chat_history' not in st.session_state:
    st.session_state.chat_history = []

# Title and description
st.title("🐟 FishyAI - Your Property Law Assistant")
st.markdown("""
<div class="description-box">
    <p>This AI assistant can help you with questions about property law. Please <strong>ONLY</strong> use this tool as a guide for information synthesis. It is not meant to be a substitute for exam preparation.</p>
    <p>As instructed by Professor Fisher, please cite that you are using this tool/an AI if you use any of the material generated by it in your exam response. Have a great exam and happy Fishing!</p>
</div>
""", unsafe_allow_html=True)

# Add sidebar with additional info
with st.sidebar:
    st.header("About FishyAI")
    st.markdown("Your AI assistant for property law questions")
    
    # Add PDF info
    st.subheader("Loaded Documents")
    loaded_pdfs = st.session_state.agent.get_loaded_pdfs()
    if loaded_pdfs:
        for pdf in loaded_pdfs:
            st.markdown(f"- {pdf}")
    else:
        st.write("No documents loaded")
    
    # Add clear chat button
    if st.button("Clear Chat History"):
        st.session_state.chat_history = []
        st.rerun()

# Display initial loading message if exists
if 'initial_load_message' in st.session_state:
    st.info(st.session_state.initial_load_message)

# Function to display custom formatted messages
def display_message(role, content, sources=None, response_time=None):
    if role == "user":
        message_class = "user-message"
        prefix = "🧑‍🎓 You"
    else:
        message_class = "assistant-message"
        prefix = "🐟 FishyAI"
    
    st.markdown(f"""
    <div class="message-container {message_class}">
        <strong>{prefix}:</strong><br/>
        {content}
    """, unsafe_allow_html=True)
    
    if sources:
        sources_html = "<br/>".join([f"• {source}" for source in sources])
        st.markdown(f"""
        <div class="sources-box">
            <strong>Sources:</strong><br/>
            {sources_html}
        </div>
        """, unsafe_allow_html=True)
    
    if response_time is not None:
        st.markdown(f"""
        <div class="response-time">
            Response time: {response_time:.2f} seconds
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("</div>", unsafe_allow_html=True)

# Display chat history with custom formatting
for message in st.session_state.chat_history:
    display_message(
        role=message["role"], 
        content=message["content"],
        sources=message.get("sources"),
        response_time=message.get("response_time")
    )

# Chat input
if prompt := st.chat_input("Ask your question about property law..."):
    # Add user message to chat history
    st.session_state.chat_history.append({"role": "user", "content": prompt})
    
    # Display user message with custom formatting
    display_message(role="user", content=prompt)
    
    # Get AI response
    with st.spinner("FishyAI is thinking..."):
        start_time = time.time()
        result = st.session_state.agent.ask_question(prompt)
        response_time = time.time() - start_time
    
    # Display assistant message with custom formatting
    display_message(
        role="assistant", 
        content=result["answer"],
        sources=result["sources"],
        response_time=response_time
    )
    
    # Add assistant response to chat history
    st.session_state.chat_history.append({
        "role": "assistant",
        "content": result["answer"],
        "sources": result["sources"],
        "response_time": response_time
    })